# Version: v1.0
FROM alpine:3.16
MAINTAINER Weien Chen "cenbiqing@gmail.com"
RUN apk add mandoc man-pages mandoc-apropos less less-doc curl curl-doc bash bash-doc bash-completion util-linux coreutils binutils findutils grep

# add dig
RUN apk add bind-tools

# add tcpdump
RUN apk add tcpdump

# add ssh
RUN apk add openssh-client

# add openssl
RUN apk add openssl

RUN export PAGER=less


