# Version: v1.0
FROM ubuntu:jammy
MAINTAINER Weien Chen "cenbiqing@gmail.com"
RUN yes | unminimize
RUN apt-get update; apt-get install -y apt-file man-db 

# apt-file to support searching packages based on binary path, like "apt-file search /usr/bin/less"
RUN apt-file update

# dig, nslookup
RUN apt-get install -y bind9-dnsutils

# less
RUN apt-get install -y less

# ip,ss, nc, curl 
RUN apt-get install -y iproute2 netcat curl 

# arp,ifconfig,route,netstat
RUN apt-get install -y net-tools

# ping
RUN apt-get install -y iputils-ping

# traceroute
RUN apt-get install -y traceroute

# tcpdump
RUN apt-get install -y tcpdump

# vim
RUN apt-get install -y vim

# ssh
RUN apt-get install -y openssh-client

CMD /bin/bash
