# Version: v1.0
FROM ubuntu:jammy
MAINTAINER Weien Chen "cenbiqing@gmail.com"
RUN apt-get update

# dig, nslookup
RUN apt-get install -y bind9-dnsutils

# less
RUN apt-get install -y less

# ip,ss, nc, curl 
RUN apt-get install -y iproute2 netcat curl 

# arp,ifconfig,route,netstat
RUN apt-get install -y net-tools

# ping
RUN apt-get install -y iputils-ping

# traceroute
RUN apt-get install -y traceroute

# tcpdump
RUN apt-get install -y tcpdump

# vim
RUN apt-get install -y vim

# ssh
RUN apt-get install -y openssh-client
